version: '3'
services:
  unmatched:
    image: calitb/unmatched
    build:
      context: .
    container_name: unmatched
    ports:
      - 3010:3000
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
